{
  "openapi": "3.0.0",
  "info": {
    "title": "PlatBlog",
    "version": "1.0.0"
  },
  "servers": [
    {
      "url": "http://127.0.0.1:8000"
    }
  ],
  "components": {
    "securitySchemes": {
      "bearerAuth": {
        "type": "http",
        "scheme": "bearer"
      }
    }
  },
  "paths": {
    "/api/posts": {
      "get": {
        "tags": [
          "default"
        ],
        "summary": "All Posts",
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "Host": {
                "schema": {
                  "type": "string",
                  "example": "127.0.0.1:8000"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "close"
                }
              },
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "PHP/8.3.12"
                }
              },
              "Cache-Control": {
                "schema": {
                  "type": "string",
                  "example": "no-cache, private"
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Fri, 07 Feb 2025 08:22:22 GMT"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json"
                }
              },
              "Access-Control-Allow-Origin": {
                "schema": {
                  "type": "string",
                  "example": "*"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "message": "Posts retrieved successfully.",
                  "data": {
                    "posts": [
                      {
                        "id": 1,
                        "title": "Post buatan 1",
                        "body": "This is the post ini for blogplat has been updated oleh dua",
                        "author_id": 1,
                        "created_at": "2025-02-07T08:20:25.000000Z",
                        "updated_at": "2025-02-07T08:21:43.000000Z",
                        "author": {
                          "id": 1,
                          "name": "dua",
                          "email": "2@gmail.com"
                        }
                      },
                      {
                        "id": 2,
                        "title": "Post buatan 2",
                        "body": "This is the post 2 keren for platblog",
                        "author_id": 1,
                        "created_at": "2025-02-07T08:22:11.000000Z",
                        "updated_at": "2025-02-07T08:22:11.000000Z",
                        "author": {
                          "id": 1,
                          "name": "dua",
                          "email": "2@gmail.com"
                        }
                      },
                      {
                        "id": 3,
                        "title": "Post buatan 3",
                        "body": "This is the post 3 keren for platblog",
                        "author_id": 1,
                        "created_at": "2025-02-07T08:22:16.000000Z",
                        "updated_at": "2025-02-07T08:22:16.000000Z",
                        "author": {
                          "id": 1,
                          "name": "dua",
                          "email": "2@gmail.com"
                        }
                      }
                    ]
                  }
                }
              }
            }
          }
        }
      },
      "post": {
        "tags": [
          "default"
        ],
        "summary": "Create Post",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "title": "Post 1",
                  "body": "This is the post 1 for blogplat"
                }
              }
            }
          }
        },
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "application/json"
          }
        ],
        "responses": {
          "201": {
            "description": "Created",
            "headers": {
              "Host": {
                "schema": {
                  "type": "string",
                  "example": "127.0.0.1:8000"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "close"
                }
              },
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "PHP/8.3.12"
                }
              },
              "Cache-Control": {
                "schema": {
                  "type": "string",
                  "example": "no-cache, private"
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Fri, 07 Feb 2025 08:20:25 GMT"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json"
                }
              },
              "Access-Control-Allow-Origin": {
                "schema": {
                  "type": "string",
                  "example": "*"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "message": "Post created successfully.",
                  "data": {
                    "title": "Post buatan 1",
                    "body": "This is the post 1 keren for platblog",
                    "author_id": 1,
                    "updated_at": "2025-02-07T08:20:25.000000Z",
                    "created_at": "2025-02-07T08:20:25.000000Z",
                    "id": 1
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "headers": {
              "Host": {
                "schema": {
                  "type": "string",
                  "example": "127.0.0.1:8000"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "close"
                }
              },
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "PHP/8.3.12"
                }
              },
              "Cache-Control": {
                "schema": {
                  "type": "string",
                  "example": "no-cache, private"
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Fri, 07 Feb 2025 08:19:53 GMT"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json"
                }
              },
              "Access-Control-Allow-Origin": {
                "schema": {
                  "type": "string",
                  "example": "*"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "message": "Unauthenticated."
                }
              }
            }
          }
        }
      }
    },
    "/api/posts/2": {
      "put": {
        "tags": [
          "default"
        ],
        "summary": "Update Post",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "body": "This is the post 2 for blogplat has been updated!"
                }
              }
            }
          }
        },
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "application/json"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "Host": {
                "schema": {
                  "type": "string",
                  "example": "127.0.0.1:8000"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "close"
                }
              },
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "PHP/8.3.12"
                }
              },
              "Cache-Control": {
                "schema": {
                  "type": "string",
                  "example": "no-cache, private"
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Fri, 07 Feb 2025 08:21:43 GMT"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json"
                }
              },
              "Access-Control-Allow-Origin": {
                "schema": {
                  "type": "string",
                  "example": "*"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "message": "Post updated successfully.",
                  "data": {
                    "post": {
                      "id": 1,
                      "title": "Post buatan 1",
                      "body": "This is the post ini for blogplat has been updated oleh dua",
                      "author_id": 1,
                      "created_at": "2025-02-07T08:20:25.000000Z",
                      "updated_at": "2025-02-07T08:21:43.000000Z",
                      "author": {
                        "id": 1,
                        "name": "dua",
                        "email": "2@gmail.com"
                      },
                      "comments": []
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "headers": {
              "Host": {
                "schema": {
                  "type": "string",
                  "example": "127.0.0.1:8000"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "close"
                }
              },
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "PHP/8.3.12"
                }
              },
              "Cache-Control": {
                "schema": {
                  "type": "string",
                  "example": "no-cache, private"
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Fri, 07 Feb 2025 08:21:20 GMT"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json"
                }
              },
              "Access-Control-Allow-Origin": {
                "schema": {
                  "type": "string",
                  "example": "*"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "message": "Unauthenticated."
                }
              }
            }
          }
        }
      }
    },
    "/api/posts/3": {
      "delete": {
        "tags": [
          "default"
        ],
        "summary": "Delete Comment",
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "Host": {
                "schema": {
                  "type": "string",
                  "example": "127.0.0.1:8000"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "close"
                }
              },
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "PHP/8.3.12"
                }
              },
              "Cache-Control": {
                "schema": {
                  "type": "string",
                  "example": "no-cache, private"
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Fri, 07 Feb 2025 08:38:49 GMT"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json"
                }
              },
              "Access-Control-Allow-Origin": {
                "schema": {
                  "type": "string",
                  "example": "*"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "message": "Comment deleted successfully."
                }
              }
            }
          },
          "403": {
            "description": "Forbidden",
            "headers": {
              "Host": {
                "schema": {
                  "type": "string",
                  "example": "127.0.0.1:8000"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "close"
                }
              },
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "PHP/8.3.12"
                }
              },
              "Cache-Control": {
                "schema": {
                  "type": "string",
                  "example": "no-cache, private"
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Fri, 07 Feb 2025 08:38:26 GMT"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json"
                }
              },
              "Access-Control-Allow-Origin": {
                "schema": {
                  "type": "string",
                  "example": "*"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "message": "Unauthorized action."
                }
              }
            }
          }
        }
      }
    },
    "/api/posts/1/comments/": {
      "get": {
        "tags": [
          "default"
        ],
        "summary": "List Comments in Post Copy",
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "Host": {
                "schema": {
                  "type": "string",
                  "example": "127.0.0.1:8000"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "close"
                }
              },
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "PHP/8.3.12"
                }
              },
              "Cache-Control": {
                "schema": {
                  "type": "string",
                  "example": "no-cache, private"
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Fri, 07 Feb 2025 08:57:36 GMT"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json"
                }
              },
              "Access-Control-Allow-Origin": {
                "schema": {
                  "type": "string",
                  "example": "*"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "message": "Comments retrieved successfully.",
                  "data": {
                    "comments": [
                      {
                        "id": 1,
                        "body": "lanjutkan broo yuhu asawda",
                        "post_id": 1,
                        "user_id": 1,
                        "created_at": "2025-02-07T08:25:15.000000Z",
                        "updated_at": "2025-02-07T08:25:15.000000Z",
                        "user": {
                          "id": 1,
                          "name": "dua",
                          "email": "2@gmail.com"
                        }
                      },
                      {
                        "id": 3,
                        "body": "yow bro ini user 3 yg baru",
                        "post_id": 1,
                        "user_id": 2,
                        "created_at": "2025-02-07T08:39:42.000000Z",
                        "updated_at": "2025-02-07T08:39:42.000000Z",
                        "user": {
                          "id": 2,
                          "name": "tiga",
                          "email": "3@gmail.com"
                        }
                      },
                      {
                        "id": 4,
                        "body": "yow bro ini user 3 yg baru lagi",
                        "post_id": 1,
                        "user_id": 2,
                        "created_at": "2025-02-07T08:39:47.000000Z",
                        "updated_at": "2025-02-07T08:39:47.000000Z",
                        "user": {
                          "id": 2,
                          "name": "tiga",
                          "email": "3@gmail.com"
                        }
                      }
                    ]
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/posts/1/comments": {
      "post": {
        "tags": [
          "default"
        ],
        "summary": "Create Comment",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "body": "keren brow"
                }
              }
            }
          }
        },
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "application/json"
          }
        ],
        "responses": {
          "201": {
            "description": "Created",
            "headers": {
              "Host": {
                "schema": {
                  "type": "string",
                  "example": "127.0.0.1:8000"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "close"
                }
              },
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "PHP/8.3.12"
                }
              },
              "Cache-Control": {
                "schema": {
                  "type": "string",
                  "example": "no-cache, private"
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Fri, 07 Feb 2025 08:25:15 GMT"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json"
                }
              },
              "Access-Control-Allow-Origin": {
                "schema": {
                  "type": "string",
                  "example": "*"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "message": "Comment created successfully.",
                  "data": {
                    "comment": {
                      "body": "lanjutkan broo yuhu asawda",
                      "post_id": 1,
                      "user_id": 1,
                      "updated_at": "2025-02-07T08:25:15.000000Z",
                      "created_at": "2025-02-07T08:25:15.000000Z",
                      "id": 1
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "headers": {
              "Host": {
                "schema": {
                  "type": "string",
                  "example": "127.0.0.1:8000"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "close"
                }
              },
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "PHP/8.3.12"
                }
              },
              "Cache-Control": {
                "schema": {
                  "type": "string",
                  "example": "no-cache, private"
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Fri, 07 Feb 2025 08:23:25 GMT"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json"
                }
              },
              "Access-Control-Allow-Origin": {
                "schema": {
                  "type": "string",
                  "example": "*"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "message": "Unauthenticated."
                }
              }
            }
          }
        }
      }
    },
    "/api/posts/1/comments/1": {
      "put": {
        "tags": [
          "default"
        ],
        "summary": "Update Comment",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "body": "keren bgt broow! (Update)"
                }
              }
            }
          }
        },
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "application/json"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "Host": {
                "schema": {
                  "type": "string",
                  "example": "127.0.0.1:8000"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "close"
                }
              },
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "PHP/8.3.12"
                }
              },
              "Cache-Control": {
                "schema": {
                  "type": "string",
                  "example": "no-cache, private"
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Fri, 07 Feb 2025 09:06:23 GMT"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json"
                }
              },
              "Access-Control-Allow-Origin": {
                "schema": {
                  "type": "string",
                  "example": "*"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "message": "Comment updated successfully.",
                  "data": {
                    "comment": {
                      "id": 6,
                      "body": "lanjutkan lololo (updated)",
                      "post_id": 2,
                      "user_id": 2,
                      "created_at": "2025-02-07T09:01:56.000000Z",
                      "updated_at": "2025-02-07T09:06:23.000000Z"
                    }
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "headers": {
              "Host": {
                "schema": {
                  "type": "string",
                  "example": "127.0.0.1:8000"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "close"
                }
              },
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "PHP/8.3.12"
                }
              },
              "Cache-Control": {
                "schema": {
                  "type": "string",
                  "example": "no-cache, private"
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Fri, 07 Feb 2025 09:01:20 GMT"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json"
                }
              },
              "Access-Control-Allow-Origin": {
                "schema": {
                  "type": "string",
                  "example": "*"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "message": "Unauthenticated."
                }
              }
            }
          },
          "404": {
            "description": "Not Found",
            "headers": {
              "Host": {
                "schema": {
                  "type": "string",
                  "example": "127.0.0.1:8000"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "close"
                }
              },
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "PHP/8.3.12"
                }
              },
              "Cache-Control": {
                "schema": {
                  "type": "string",
                  "example": "no-cache, private"
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Fri, 07 Feb 2025 09:10:59 GMT"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json"
                }
              },
              "Access-Control-Allow-Origin": {
                "schema": {
                  "type": "string",
                  "example": "*"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "message": "Data not found."
                }
              }
            }
          }
        }
      }
    },
    "/api/register": {
      "post": {
        "tags": [
          "default"
        ],
        "summary": "Register",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "name": "3",
                  "email": "3@gmail.com",
                  "password": "3",
                  "password_confirmation": "3"
                }
              }
            }
          }
        },
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "application/json"
          }
        ],
        "responses": {
          "201": {
            "description": "Created",
            "headers": {
              "Host": {
                "schema": {
                  "type": "string",
                  "example": "127.0.0.1:8000"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "close"
                }
              },
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "PHP/8.3.12"
                }
              },
              "Cache-Control": {
                "schema": {
                  "type": "string",
                  "example": "no-cache, private"
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Fri, 07 Feb 2025 08:26:35 GMT"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json"
                }
              },
              "Access-Control-Allow-Origin": {
                "schema": {
                  "type": "string",
                  "example": "*"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "message": "Registered successfully.",
                  "data": {
                    "user": {
                      "name": "tiga",
                      "email": "3@gmail.com",
                      "updated_at": "2025-02-07T08:26:35.000000Z",
                      "created_at": "2025-02-07T08:26:35.000000Z",
                      "id": 2
                    }
                  }
                }
              }
            }
          },
          "422": {
            "description": "Unprocessable Content",
            "headers": {
              "Host": {
                "schema": {
                  "type": "string",
                  "example": "127.0.0.1:8000"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "close"
                }
              },
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "PHP/8.3.12"
                }
              },
              "Cache-Control": {
                "schema": {
                  "type": "string",
                  "example": "no-cache, private"
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Fri, 07 Feb 2025 08:26:05 GMT"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json"
                }
              },
              "Access-Control-Allow-Origin": {
                "schema": {
                  "type": "string",
                  "example": "*"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "message": "The email field must be a valid email address. (and 1 more error)",
                  "errors": {
                    "email": [
                      "The email field must be a valid email address."
                    ],
                    "password": [
                      "The password field confirmation does not match."
                    ]
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/login": {
      "post": {
        "tags": [
          "default"
        ],
        "summary": "Login",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "email": "fauzan@gmail.com",
                  "password": "fauzan"
                }
              }
            }
          }
        },
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "application/json"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "Host": {
                "schema": {
                  "type": "string",
                  "example": "127.0.0.1:8000"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "close"
                }
              },
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "PHP/8.3.12"
                }
              },
              "Cache-Control": {
                "schema": {
                  "type": "string",
                  "example": "no-cache, private"
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Fri, 07 Feb 2025 08:19:32 GMT"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json"
                }
              },
              "Access-Control-Allow-Origin": {
                "schema": {
                  "type": "string",
                  "example": "*"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "message": "Logged in successfully.",
                  "data": {
                    "token": "1|P6fUoAgKG2cozc9uc5C8PtmdlHmQB8inmM7uuwCk7c28da52"
                  }
                }
              }
            }
          },
          "422": {
            "description": "Unprocessable Content",
            "headers": {
              "Host": {
                "schema": {
                  "type": "string",
                  "example": "127.0.0.1:8000"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "close"
                }
              },
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "PHP/8.3.12"
                }
              },
              "Cache-Control": {
                "schema": {
                  "type": "string",
                  "example": "no-cache, private"
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Fri, 07 Feb 2025 08:27:09 GMT"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json"
                }
              },
              "Access-Control-Allow-Origin": {
                "schema": {
                  "type": "string",
                  "example": "*"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "message": "Invalid credentials.",
                  "errors": {
                    "email": [
                      "Invalid credentials."
                    ]
                  }
                }
              }
            }
          }
        }
      }
    },
    "/api/logout": {
      "post": {
        "tags": [
          "default"
        ],
        "summary": "Logout",
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "example": {
                  "name": "user1",
                  "email": "user1@gmail.com",
                  "password": "user1",
                  "password_confirmation": "user1"
                }
              }
            }
          }
        },
        "security": [
          {
            "bearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "Accept",
            "in": "header",
            "schema": {
              "type": "string"
            },
            "example": "application/json"
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "headers": {
              "Host": {
                "schema": {
                  "type": "string",
                  "example": "127.0.0.1:8000"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "close"
                }
              },
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "PHP/8.3.12"
                }
              },
              "Cache-Control": {
                "schema": {
                  "type": "string",
                  "example": "no-cache, private"
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Fri, 07 Feb 2025 08:27:33 GMT"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json"
                }
              },
              "Access-Control-Allow-Origin": {
                "schema": {
                  "type": "string",
                  "example": "*"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "message": "Logged out successfully."
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized",
            "headers": {
              "Host": {
                "schema": {
                  "type": "string",
                  "example": "127.0.0.1:8000"
                }
              },
              "Connection": {
                "schema": {
                  "type": "string",
                  "example": "close"
                }
              },
              "X-Powered-By": {
                "schema": {
                  "type": "string",
                  "example": "PHP/8.3.12"
                }
              },
              "Cache-Control": {
                "schema": {
                  "type": "string",
                  "example": "no-cache, private"
                }
              },
              "Date": {
                "schema": {
                  "type": "string",
                  "example": "Fri, 07 Feb 2025 08:27:56 GMT"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string",
                  "example": "application/json"
                }
              },
              "Access-Control-Allow-Origin": {
                "schema": {
                  "type": "string",
                  "example": "*"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "type": "object"
                },
                "example": {
                  "message": "Unauthenticated."
                }
              }
            }
          }
        }
      }
    }
  }
}